### ISSUE TITLE
Pass TeslaMate PUT requests to TeslaMate from TeslaMateApi

### ISSUE THREAD

**Issue by tobiasehlert** [tobiasehlert/teslamateapi#10]
> For such cases there is `PUT /api/car/1/logging/resume`. It will instruct TeslaMate to resume logging and increase the polling interval for a short period.

Pass TeslaMate PUT requests to TeslaMate from TeslaMateApi

https://github.com/adriankumpf/teslamate/blob/00339cff452df4d56659d53cdd9e79cfe4721180/lib/teslamate_web/router.ex#L38

_Originally posted by @tobiasehlert in https://github.com/adriankumpf/teslamate/discussions/1433#discussioncomment-473385_

**Comment by LelandSindt** [comment]
how do you feel about exposing 

PUT `/api/v1/cars/:CarID/logging/resume`
PUT `/api/v1/cars/:CarID/logging/suspend`

and requiring the same `API_TOKEN` that the commands require?

**Comment by tobiasehlert** [comment]
> how do you feel about exposing
> 
> PUT `/api/v1/cars/:CarID/logging/resume`
> PUT `/api/v1/cars/:CarID/logging/suspend`

I think it should be similar to the commands part, except that it's passed to TeslaMate instead of Tesla owner-api :)

> and requiring the same `API_TOKEN` that the commands require?

I you ask me, all actions that **do** something should be utilizing the API_TOKEN.

I'm thinking to perform a _resume_ also when doing wake_up.. or what you think @LelandSindt?

**Comment by LelandSindt** [comment]
https://github.com/gaussmeter/teslamateapi/commit/5ae521caba18514f66253040a2ecfd8c1cbbe4dd -- adds support for teslamate logging endpoints.

@tobiasehlert, I stopped short of making `wake_up` also call `resume` as it required more refactoring and thinking than I was up for tonight. --- I am not opposed but I do go back and forth... should they be tightly coupled, or left independent... would I ever want to call `wake_up` _without_ instructing TeslaMate to resume logging..

**Comment by michaeldyrynda** [comment]
I'm managing charging during the day based on solar production and home battery capacity. I've only built integration with what's in TeslaMateAPI, rather than TeslaMate directly, so if the car is suspended, I have to manually wake TeslaMate before letting my automation take over.

Would be good to see this brought into the API 🙏

**Comment by LelandSindt** [comment]
I went ahead and opened a PR. 

I tried to wrap my head around how the `wake` and `resume` commands could be coupled but nothing felt right. 

... maybe a third end point  ~ `wake_and_resume` :shrug: 

--- I am inclined to think that they are best left independent.

**Comment by michaeldyrynda** [comment]
I'm ok with making two separate calls - they're both network-local, so not like there's any latency or other overhead to making the HTTP request anyway. Thanks for the PR, hopefully we see it soon :)

**Comment by tobiasehlert** [comment]
created separate branch [feature-10-logging-commands](https://github.com/tobiasehlert/teslamateapi/tree/feature-10-logging-commands) for this feature.
had some comments on https://github.com/tobiasehlert/teslamateapi/pull/34 for @LelandSindt

**Comment by tobiasehlert** [comment]
Thanks for the PR @LelandSindt 👍 

Shall we use the PORT env variable from TeslaMate container or use a separate one anyways?
For me this looks fine for now, so I could merge it.

**Comment by tobiasehlert** [comment]
@michaeldyrynda do you want to test the feature before merging to latest?
You can pull the docker image with tag `feature-10-logging-commands` and let us know if it works as expected.

**Comment by LelandSindt** [comment]
@tobiasehlert I am sorry I don't understand. Are you talking about a variable that you can be pulled in from the docker-compose.yaml?  

Reviewing this morning, I am inclined to change TESLAMATE_FQDN to TESLAMATE_HOST to better align with DATABASE_HOST

**Comment by tobiasehlert** [comment]
@LelandSindt, what I was considering is to use `PORT `instead of `TESLAMATE_PORT `instead, since people might specify the `PORT `variable in .env already, but that is maybe stupid way to go.
Maybe it's a better approach as you suggest to go with `TESLAMATE_PROT`, `TESLAMATE_HOST `and `TESLAMATE_PORT`

With PORT I was thinking of those available here:
https://docs.teslamate.org/docs/configuration/environment_variables

**Comment by LelandSindt** [comment]
I think that PORT and PROT are too similar... after reviewing the DATABASE_* environment variables I went with... 

TESLAMATE_SSL false
TESLAMATE_HOST teslamate
TESLAMATE_PORT 4000

#48 

If you have strong opinions that differ, I am open to them.

**Comment by michaeldyrynda** [comment]
Hey @tobiasehlert - just had a chance to test this and resume/suspend logging works as it says on the tin.
