### ISSUE TITLE
sql: Scan error on column index 4, name "efficiency": converting NULL to float64 is unsupported

### ISSUE THREAD

**Issue by gehoida** [tobiasehlert/teslamateapi#128]
When calling "http://myserver:8080/api/v1/cars" or "http://myserver:8080/api/v1/cars/1" I  the following error is logged in my docker container "sql: Scan error on column index 4, name "efficiency": converting NULL to float64 is unsupported". Other endpoints work,

**Comment by gehoida** [comment]
As soon as the efficiency-board showed data, the issue disappeared. Then the data in the db is not NULL any longer.

**Comment by tobiasehlert** [comment]
Hi @gehoida,

Do you have a brand new TeslaMate installation, so that the value was not populated yet? What Tesla model do you have?
I've created PR #129 that should resolve this issue in future.

Thanks,
Tobias

**Comment by gehoida** [comment]
Yes, a new Installation for my model 3. As soon as efficiency is calculated, the api works as expected.

**Comment by tobiasehlert** [comment]
Verified with a new installation and the PR does solve the issue.
Thanks for reporting @gehoida 👍

**Comment by tobiasehlert** [comment]
Released [v1.12.0](https://github.com/tobiasehlert/teslamateapi/releases/tag/v1.12.0) that contains the fix :)
