### ISSUE TITLE
TeslaMateAPICarsDrivesDetailsV1 appears broken in v1.13.1

### ISSUE THREAD

**Issue by ItsGiles** [tobiasehlert/teslamateapi#136]
Recently updated to latest from v1.9.0 and discovered the TeslaMateAPICarsDrivesDetailsV1 was no longer returning drive details, instead returning a blank dataset for 'drive'.

Example result from v1.13.1:

GET /api/v1/cars/1/drives/1443

`{"data":{"car":{"car_id":1,"car_name":"Tesla-1"},"drive":{"drive_id":0,"start_date":"","end_date":"","start_address":"","end_address":"","odometer_details":{"odometer_start":0,"odometer_end":0,"odometer_distance":0},"duration_min":0,"duration_str":"","speed_max":0,"speed_avg":0,"power_max":0,"power_min":0,"battery_details":{"start_usable_battery_level":0,"start_battery_level":0,"end_usable_battery_level":0,"end_battery_level":0,"reduced_range":false,"is_sufficiently_precise":false},"range_ideal":{"start_range":0,"end_range":0,"range_diff":0},"range_rated":{"start_range":0,"end_range":0,"range_diff":0},"outside_temp_avg":0,"inside_temp_avg":0,"drive_details":null},"units":{"unit_of_length":"km","unit_of_temperature":"C"}}}`

Reverting to v1.12.1 rectifies the problem with the full 'drive' data being returned as expected.

**Comment by tobiasehlert** [comment]
Nice catch @ItsGiles!
I'll look into this immediately :)

**Comment by tobiasehlert** [comment]
I have rewritten some things in #134 and with that, the issue disappeared from me. It's merged into main now, but I'll bump a new version in a couple of minutes. 
Thanks for reporting!

**Comment by tobiasehlert** [comment]
Released [v1.13.2](https://github.com/tobiasehlert/teslamateapi/releases/tag/v1.13.2) now, please get back to me with how it works.

**Comment by ItsGiles** [comment]
> Released [v1.13.2](https://github.com/tobiasehlert/teslamateapi/releases/tag/v1.13.2) now, please get back to me with how it works.

Just updated to latest (v1.13.2) and the problem is gone! Looking good now!
