### ISSUE TITLE
"no info on this car ID" on status - but all other functions work!

### ISSUE THREAD

**Issue by chamsters** [tobiasehlert/teslamateapi#185]
Hi there!

Any idea what I could be doing wrong? I've run through all your various query tools and all have worked - e.g. http://xxx.xxx.xxx.xxx:8080/api/v1/cars/1/charges show me all the charges. But http://xxx.xxx.xxx.xxx:8080/api/v1/cars/1/status yields the error "no info on this car ID"

Any idea at all what the issue could be?

Thanks!

**Comment by tobiasehlert** [comment]
Hi @chamsters,

My initial thought is that it's probably the configuration of the MQTT setting that is either missing or faulty.
Are you seeing any entry in the log of MQTT and/or TeslaMateApi when restarting the TeslaMateApi container?

Regards,
Tobias

**Comment by chamsters** [comment]
So, oddly - it started working after my first charge. I'm guessing that I had hooked this up to a new instance of teslamate which was still seeding a lot of initial data, hence the error?

**Comment by chamsters** [comment]
Thanks for the help!
