### ISSUE TITLE
manifest for docker.io/tobiasehlert/teslamateapi:latest not found

### ISSUE THREAD

**Issue by chrisbergeron** [tobiasehlert/teslamateapi#227]
Received error:

`
[+] Running 0/1
 ⠴ teslamateapi Pulling
manifest for docker.io/tobiasehlert/teslamateapi:latest not found
`

When using docker-compose.yml.  I did a `docker pull -a` to get all images and the latest version I see is `1.15.0`.  My fix was to change the docker-compose.yml contents:

`tobiasehlert/teslamateapi:latest` to `tobiasehlert/teslamateapi:1.15.0`

**Comment by tobiasehlert** [comment]
Hi @chrisbergeron,

Sorry for not responding earlier, but the `latest` tag should be working as expected.
Also, the latest version is [v1.16.1](https://github.com/tobiasehlert/teslamateapi/releases/tag/v1.16.1) for TeslaMateApi, so you might want to consider upgrading to that instead :)

Setting issue to closed, but get back if you have some more follow up question regarding this.

Kind regards,
Tobias
