### ISSUE TITLE
Feature request: Details of current charge

### ISSUE THREAD

**Issue by MikeBishop** [tobiasehlert/teslamateapi#228]
For any past charges, the array of `charge_details` objects describing the samples of the charge session can be retrieved.  Is it possible to expose the array of details so far from an ongoing charge session?

**Comment by tobiasehlert** [comment]
Hello @MikeBishop,

You can retrieve information from the ongoing charge by requesting the `/api/v1/cars/:CarID/status` endpoint.
When a charge is ongoing, you should find details under the `data.status.charging_details` :)

The details you can find there are the ones provided in MQTT by [TeslaMate](https://github.com/adriankumpf/teslamate), which are following:
https://github.com/tobiasehlert/teslamateapi/blob/10c295f7a345ccb76f6005d8a1de8d95c49e3ec4/src/v1_TeslaMateAPICarsStatus.go#L411-L422

Get back if there are some more outstanding questions, I'll set the issue to closed until then.

Kind regards,
Tobias

**Comment by MikeBishop** [comment]
I don't see a way under there to identify the start time of the current charge, nor the power numbers over the course of it; that's just an instantaneous view. When the charge is complete and added to charge details, you can fetch a series of instantaneous views with their timestamps, but the series that has been assembled so far seems to be inaccessible.
