### ISSUE TITLE
best way to troubleshoot {"error":"Unable to load cars."}

### ISSUE THREAD

**Issue by GERLion76** [tobiasehlert/teslamateapi#240]
The setup has worked so far. For the queries 

/api/v1/
```json
{
	"message": "TeslaMateApi v1 runnnig..",
	"path": "/api/v1"
}
```

/api/ping
```json
{
	"message": "pong"
}
```

/api/v1/globalsettings
```json
{
	"data": {
		"settings": {
			"setting_id": 1,
			"account_info": {
				"inserted_at": "2022-11-18T11:12:11+01:00",
				"updated_at": "2023-09-12T14:34:54+02: 00"
			},
			"teslamate_units": {
				"unit_of_length": "km",
				"unit_of_temperature": "C"
			},
			"teslamate_webgui": {
				"preferred_range": "rated",
				"language": "en"
			},
			"teslamate_urls": {
				"base_url": "http://192. 168.178.181:4000",
				"grafana_url": "http://192.168.178.181:3000"
			}
		}
	}
}
```

i get correct values back. But as soon as I use e.g. `/api/v1/cars` as query, I get only following response:
```json
{
	"error": "Unable to load cars."
}
```

What is the best way to find the error? Can I check the communication to the database somehow? Thanks in advance!

**Comment by GERLion76** [comment]
Docker logs:

2023/09/12 15:29:41.839985 [info] TeslaMateAPIGlobalsettingsV1 - (/api/v1/globalsettings) executed successfully.
[GIN] 2023/09/12 - 15:29:41 | 200 |     978.406µs | 192.168.178.134 | GET      "/api/v1/globalsettings"
2023/09/12 15:30:07.480008 [error] TeslaMateAPICarsV1 - (/api/v1/cars). Unable to load cars.; sql: Scan error on column index 8, name "name": converting NULL to string is unsupported
[GIN] 2023/09/12 - 15:30:07 | 200 |    1.658839ms | 192.168.178.134 | GET      "/api/v1/cars"

**Comment by tobiasehlert** [comment]
hello @GERLion76,

Have you set the name of your car or is it brand new?
If so, this could be fixed with #226 that resolves _NullString_.

Regards,
Tobias

**Comment by GERLion76** [comment]
Hello @tobiasehlert ,

thank you for your answer! You were right, I had not yet set a name for my car. To test I have now set a name, but the behavior is still identical. Can I do something myself to fix the problem or do I have to wait for a fix for #226? Thanks a lot already.

**Comment by tobiasehlert** [comment]
hi @GERLion76,

Please try to restart your teslamateapi container to see, if the issue is resolved.

If not;
You could try the docker image with tag `feature-address-details` and see if the error is disappearing.

If not;
Please run following psql query to see what's in the database so that we can see that the name is populated:
```console
select id, model, name from cars;
```

Regards,
Tobias

**Comment by GERLion76** [comment]
Hi @tobiasehlert, 

you were right again. Restarted all containers again and now it works like a charm. Thanks for your work and support!
