### ISSUE TITLE
Bug: active_route details not shown in /cars/ID/status

### ISSUE THREAD

**Issue by Zegorax** [tobiasehlert/teslamateapi#294]
When the vehicle has an active destination set, the information sent from Teslamate to the MQTT endpoint `teslamate/cars/1/active_route` is as follows:

```json
{
  "error": null,
  "location": {
    "latitude": 0.00000,
    "longitude": 0.0000
  },
  "destination": "Test",
  "energy_at_arrival": 81,
  "miles_to_arrival": 1.659566,
  "minutes_to_arrival": 7.716667,
  "traffic_minutes_delay": 0
}
```

However, it is not appearing in `/api/v1/cars/1/status`. Would it be possible to check ?

I inspected the code and found a few references to this implementation, however due to my lack of knowledge of the language and the repo, I was not able to troubleshoot why it was not displayed.

In the logs, it says:
```log
api-1  | 2024/07/22 17:55:00.506031 [warning] TeslaMateAPICarsStatusV1 mqtt.MessageHandler issue.. extraction of data for active_route not implemented!
api-1  | 2024/07/22 17:56:16.594330 [warning] TeslaMateAPICarsStatusV1 mqtt.MessageHandler issue.. extraction of data for active_route not implemented!
api-1  | 2024/07/22 17:58:18.826053 [warning] TeslaMateAPICarsStatusV1 mqtt.MessageHandler issue.. extraction of data for active_route not implemented!
api-1  | 2024/07/22 18:00:21.546762 [warning] TeslaMateAPICarsStatusV1 mqtt.MessageHandler issue.. extraction of data for active_route not implemented!
api-1  | 2024/07/22 18:02:23.786720 [warning] TeslaMateAPICarsStatusV1 mqtt.MessageHandler issue.. extraction of data for active_route not implemented!
api-1  | 2024/07/22 18:04:26.177966 [warning] TeslaMateAPICarsStatusV1 mqtt.MessageHandler issue.. extraction of data for active_route not implemented!
```

Thanks a lot in advance!

**Comment by Zegorax** [comment]
Never mind! I just tried with the `:edge` tag image in GHCR, and it worked. I did not notice that it was not yet relased.

**Comment by tobiasehlert** [comment]
hi @Zegorax,

Thanks for reporting. But as you already noted, this is resolved on the edge image.
I'll push a new release maybe later today or tomorrow, I had the hope to get #191 in place as well before that.

Regards,
Tobias
