### ISSUE TITLE
API Unavailable on Other Ports

### ISSUE THREAD

**Issue by alecdoconnor** [tobiasehlert/teslamateapi#36]
When setting this up on two systems, I used port `4001`, `8086`, and a few others since port `8080` was taken. After updating the `docker-compose.yml` for each port, I only ever saw success with port `8080` (after disabling the other server on port 8080). Is it possible that the port is hard-coded somewhere and not entirely following the `docker-compose.yml`?

**Comment by alecdoconnor** [comment]
https://github.com/tobiasehlert/teslamateapi/blob/fee87903cdf762b07b44bdb416ed12b48dee1b89/Dockerfile
It looks like port 8080 is hard-coded in the dockerfile

**Comment by LelandSindt** [comment]
I don't use docker compose often these days, but after reviewing the [documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#ports)  

When attempting to expose `teslamateapi` on port 4001, your docker-compose.yaml should look something like this...
```
services:
  teslamateapi:
  [.. omitted ..]
    ports:
      - 4001:8080
```

The container port will always be 8080, and you should be able to shift the host port to fit your needs.  Is my understanding of what you are trying to do correct?

**Comment by michaeldyrynda** [comment]
This should be correct; it’s what I’m doing

**Comment by alecdoconnor** [comment]
It looks like this was my mistake, thank you for charifying!

**Comment by tobiasehlert** [comment]
Awesome it works for you now @alecdoconnor and thanks to @LelandSindt for helping out so quick 👍
