### ISSUE TITLE
Drive Speeds Not Being Converted

### ISSUE THREAD

**Issue by alecdoconnor** [tobiasehlert/teslamateapi#38]
DriveDetails currently converts metric to imperial, but Drive does not. This shows a user's max and average speed as being much higher when they are using "mi" for distance, since it is still showing speed in km/hr

*Pull Request*
https://github.com/tobiasehlert/teslamateapi/pull/37

**Comment by tobiasehlert** [comment]
This should be fixed now with your PR.
Thanks @alecdoconnor
