### ISSUE TITLE
New data only every two minutes

### ISSUE THREAD

**Issue by pkuehnel** [tobiasehlert/teslamateapi#4]
Is it right, that data is refreshed only every two minutes? When I look in the database there are values every few seconds but via API I only get new values after two minutes or even later.

**Comment by tobiasehlert** [comment]
Hi @pkuehnel,

The data is retrieved directly from the postgres database every request you do towards the API, so it should be kind of immediately when getting data from the endpoint.

What endpoint are you trying to reach?

Regards,
Tobias

**Comment by pkuehnel** [comment]
Hi,
i was trying the `cars/1/status` endpoint and was especilly looking at the charge_energy_added value during charging the car. I had a higher value in the database and called the endpoint after looking in the database. I double checked the database then, but the lower value never came again so it was no flickering in the Tesla API.

**Comment by tobiasehlert** [comment]
Hi @pkuehnel,

The code that is executed does connect to the MQTT service and collects the latest status from it. It could be that the data in postgres might be faster than the data that is populated to MQTT my TeslaMate, but that is just a guess.

So yeah.. I guess there is not much to do than having a slight delay in data that is returned by MQTT.

@adriankumpf can maybe tell how the data is populated? :) 

Regards,
Tobias

**Comment by pkuehnel** [comment]
Hmm... I can not reproduce the issue anymore. The VM where TeslaMate was running on ran out of disk space a few hours after I had the issue, since I enlarged the disk the issue is gone, probably it hat somethink to do with that.

**Comment by tobiasehlert** [comment]
Thanks for letting me know @pkuehnel and lets hope that was the reason for that behavior. :)
