### ISSUE TITLE
EndDate Can Be NULL, Causing Failed Charges Endpoint

### ISSUE THREAD

**Issue by alecdoconnor** [tobiasehlert/teslamateapi#43]
It's possible to have incomplete charges with missing EndDate. These aren't always valid objects either, but they shouldn't prevent the Charges endpoint from providing data.
I believe this can happen when TeslaMate is offline when the charging cycle ends. I am not sure if it's also possible if the vehicle is actively charging.

**Error:**
`sql: Scan error on column index 2, name "end_date": converting NULL to string is unsupported`

*Pull Request*
https://github.com/tobiasehlert/teslamateapi/pull/40

**Comment by alecdoconnor** [comment]
For my last few issues, I created issues and pull requests separately. Please let me know if this isn't standard practice!

**Comment by tobiasehlert** [comment]
> For my last few issues, I created issues and pull requests separately. Please let me know if this isn't standard practice!

Totally fine with separated issues and pull requests :)

**Comment by tobiasehlert** [comment]
Hmm.. got a bit messy since I tagged wrong PR and merged. Reverted it but now is the question on how to fix it.

Please do name the PRs something better than _patch-X_ 😄

**Comment by tobiasehlert** [comment]
Back to the issue @alecdoconnor, what does the database return on that row that you got?

It would actually have a date set, except if the charge is being corrupt somehow.
What does the TeslaMate grafana view of charges say?

**Comment by alecdoconnor** [comment]
> Hmm.. got a bit messy since I tagged wrong PR and merged. Reverted it but now is the question on how to fix it.
> 
> Please do name the PRs something better than _patch-X_ 😄

Will do, sorry for missing the title!

It does appear that the two charges are corrupted, as even charges that are in progress don't report with the API. I attempted to go to the URL of the next charge and it only populated after charging ended; prior to that it was a 502 error, I believe.
So potentially the solution should be to drop any mal-formed charges when populating the response. What are your thoughts?

Currently I receive a 502 proxy error since a fatal error is called when End_Date is missing.

**Comment by alecdoconnor** [comment]
<img width="1482" alt="Screen Shot 2021-05-04 at 9 14 09 AM" src="https://user-images.githubusercontent.com/20458718/117008889-2d11ca80-acb9-11eb-927a-6bc16607f81d.png">
Here's the data for about 10 charges. It's clear that id = 2 and 3 are invalid charges. I'm going to submit a new PR, let me know what you think

**Comment by alecdoconnor** [comment]
Pull request: https://github.com/tobiasehlert/teslamateapi/pull/47

**Comment by tobiasehlert** [comment]
@alecdoconnor sorry, haven't had time yet

Regarding skipping malformed rows.. this only applies to the end_date being null and this could still be on other places as well.
Have you tried the same thing on the charge details view? do we need to add a fix for that as well?

Created a separate branch [bug-43](https://github.com/tobiasehlert/teslamateapi/tree/bug-43) for this, so we can test the code enought before merging.
In Docker Hub there is a label with `bug-43` available for testing :)

**Comment by tobiasehlert** [comment]
pipeline seems to fail when building the code.. I'll check into it later :)

**Comment by alecdoconnor** [comment]
@tobiasehlert I did not try it on the charge detail view, but I can confirm the issue exists in charge detail too. As for a solution, I'm not sure what would be best. Since it's just one charge, we couldn't just skip it. Potentially we throw an error in the API response and call it a day? I'll try to put another PR together and set the base to https://github.com/tobiasehlert/teslamateapi/tree/bug-43 so they can work together. Let me know what you think.

Not sure about the build failing. I'm pretty sure this is how you use `continue` in Go, but I could be wrong.

**Comment by alecdoconnor** [comment]
@tobiasehlert Have you had a chance to look into the pipeline failure?
While my car is charging the entire Charges endpoint fails.

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server
```

**Comment by tobiasehlert** [comment]
@alecdoconnor, since i merged #51, I've added your comment and my reply in here:

> _Reason_
> A detailed charge is malformed if the end_date is missing in SQL. It's also possible a charge that is in progress will be missing this value as well, in which case this detailed charge isn't populated with data.
> 
> _Better Solutions_ (long term)
> Adjust error handling across the API:
> 
> * _Opt 1:_ Instead of `ValidResponse` being a boolean, replace with `ResponseError`. Change the if statement at the bottom of each file to check for the `ResponseError`'s existence instead of `if ValidResponse {...} else {...}`. Remove all log.Fatal(err) so that the API can still return responses gracefully, and set status to 200 OK since the response will still technically be HTTP valid. Break execution of further steps and return the meaningful ResponseError in the API
> * _Opt 2:_ For simplicity, create a functions like this and call it (along with an early `return`) wherever a fatal error is currently used (or `ValidResponse` never set to true). Then remove `ValidResponse` entirely and adjust the `if` statement at the bottom of every API file to only run the first condition.
> 
> ```
> func TeslaMateAPIHandleErrorResponse(c *gin.Context, s string) {
>     log.Println("[error] TeslaMateAPICarsChargesDetailsV1 " + c.Request.RequestURI + " error in execution! " + s)
>     c.JSON(http.StatusOK, gin.H{"error": s})
> }
> func TeslaMateAPIHandleSuccessResponse(c *gin.Context, j JSONData) {
>     log.Println("[info] TeslaMateAPICarsChargesDetailsV1 " + c.Request.RequestURI + " executed successful.")
>     c.JSON(http.StatusOK, j)
> }
> ```
> 
> If you're interested, I'd be happy to put together a sample PR

You have actually a good point there.. that might be better to create a better error-handling in the response.
Opt 2 seems pretty good an clean to me.. why not go for that? Or do you think Opt 1 would be a better option?

@LelandSindt, what do you think of the two options?
You've made good contributions and would like to hear your input here :)

**Comment by tobiasehlert** [comment]
Hi @alecdoconnor,

Sorry for the slow work on this case, but have currently a little too much :)

Anyhow.. I've walked through [bug-48](https://github.com/tobiasehlert/teslamateapi/tree/bug-43) branch and the code you wrote was not valid. So I thought a little about the issue and that those charges are broken, since there is no `end_date`, so I thought it would be better to implement the skipping of `end_date` similar to drives.
So now I've applied that patch to the branch and you could test the docker image with tag `bug-43` and let me know what you think.

Regards,
Tobias

**Comment by alecdoconnor** [comment]
Of course, I know exactly what you mean
I'll give `bug-43` a test, thank you!
Regarding https://github.com/tobiasehlert/teslamateapi/pull/58, I submitted an update to correct the typo. I believe this improvement is still valid since an empty data set will still be a valid response. Let me know what you think!

**Comment by alecdoconnor** [comment]
@tobiasehlert The `bug-43` branch works great for me!
