### ISSUE TITLE
Direct access to certain values?

### ISSUE THREAD

**Issue by theskyisthelimit** [tobiasehlert/teslamateapi#5]
Thank you very much for this cool utility.

Is it possible to access a value directly? So if I want for example only the values of car_versions?

**Comment by tobiasehlert** [comment]
Hi @theskyisthelimit,

No, there is no possibility to just get one value from the API at any endpoint. You would have to call for example the status endpoint and get the appropriate JSON field with e.g. the version in your case. :)

Regards,
Tobias

**Comment by tobiasehlert** [comment]
Closing the issue. Get back to be if you have any further question :)
