### ISSUE TITLE
error strings should not end with punctuation or a newline (ST1005)

### ISSUE THREAD

**Issue by tobiasehlert** [tobiasehlert/teslamateapi#61]
**go-staticcheck reports:**
error strings should not end with punctuation or a newline (ST1005)

**line in code:**
https://github.com/tobiasehlert/teslamateapi/blob/a9feeee22872511d70f1690183681c824190ce8b/src/v1_TeslaMateAPICarsStatus.go#L84

**documentation link:**
https://staticcheck.io/docs/checks#ST1005

**Comment by tobiasehlert** [comment]
@LelandSindt do you know why this is not happy?
Maybe we should switch to another log handler.. like logrus or something?

**Comment by LelandSindt** [comment]
or just remove the `!` :man_shrugging:

**Comment by tobiasehlert** [comment]
Tried with `.`.. but yeah.. removed and now it doesn't complain 🎉
