### ISSUE TITLE
Charge details giving an error

### ISSUE THREAD

**Issue by tobiasehlert** [tobiasehlert/teslamateapi#68]
Hey @tobiasehlert,

I think I have the same problem. Since 4 weeks I can access the charges data. Now I got the error " Empty reply from server
"
![Bildschirmfoto 2021-05-31 um 17 34 05](https://user-images.githubusercontent.com/62521486/120215987-b96ec900-c236-11eb-8d13-807bdf551acb.png)

What should I do?

_Originally posted by @idominiki in https://github.com/tobiasehlert/teslamateapi/issues/18#issuecomment-851564620_

**Comment by tobiasehlert** [comment]
Hi @idominiki,

What version of TeslaMate and TeslaMateApi are you running?
Are other endpoints working as expected?
Have you checked in the database if you see something weird in the charges table?
Are you seeing charges in Grafana or is there some error showing up as well?
What are the logs saying in the TeslaMateApi container? Something abnormal there?

Regards,
Tobias

**Comment by idominiki** [comment]
Hi @tobiasehlert 
TeslaMateAPI v1.7.0 and TeslaMate v1.22.0.
All other Endpoints running perfect!
The Database seems okay and grafana working without problems. I can see all charges.

I just saw this error If I curl the charges endpoint "2021/06/01 07:38:26.865215 sql: Scan error on column index 2, name "end_date": converting NULL to string is unsupported"

Greets,
Dominik

**Comment by tobiasehlert** [comment]
Hi @idominiki,

Alright, then it looks like this should be fixed with [bug-48](https://github.com/tobiasehlert/teslamateapi/tree/bug-43) branch.. you can try and run the docker image labled with `bug-48` and confirm if it works for you :)

Regards,
Tobias

**Comment by tobiasehlert** [comment]
actually merged it to main now.. so pull the _latest_ image _version 1.8.0_ and it should work for you :)
