### ISSUE TITLE
Extraction of Data for Power Not Implemented

### ISSUE THREAD

**Issue by alecdoconnor** [tobiasehlert/teslamateapi#84]
Every time an MQTT message with `topic == power` is sent, the following error is printed to the console:

`[warning] TeslaMateAPICarsStatusV1 mqtt.MessageHandler issue.. extraction of data for power not implemented!`

**Comment by alecdoconnor** [comment]
Actually, I went to create a PR to fix it, but the code looks right. I will verify I am on the most recent version and respond here later.

**Comment by tobiasehlert** [comment]
Ah nice catch.. I'll send my wife on a tour with our car to see if I get the error..
I've not noticed anything yet in my logs at least 🤔

**Comment by alecdoconnor** [comment]
I tested on another drive after pulling changes and it's fixed. That makes sense since the code looked complete. I'll close this!

**Comment by tobiasehlert** [comment]
Ah alright great! Good to know that it wasn't broke 😄
