### ISSUE TITLE
TeslaMate API commands - how to 

### ISSUE THREAD

**Issue by denisjoshua** [tobiasehlert/teslamateapi#95]
Hi there, 
I use the TeslaMate also in order to have some info for my NodeRed implementation of charging my Tesla M3 car. 
And until now, in order to start/stop charging I always use the [node-red-contrib-tesla](https://flows.nodered.org/node/node-red-contrib-tesla)  ...but this node sometime is not work. (like now for example) 

So I try to implement the [Commands](https://github.com/tobiasehlert/TeslaMateApi#commands) 
and I inserted this code in my docker-compose file and pull/compose again: 
```
      - ENABLE_COMMANDS=true
      - COMMANDS_CHARGING=true

```

My question now is... how can I send a charging start/stop to my Tesla car please ? 
Is possible to have a MQTT topic like "charging_start_stop" and change this topic from my Node-Red flow 
in order to start/stop charging ? 
Or maybe have a command MQTT topic and use it in order to send more commands type. 

I'm not a programmer so I don't know how to implement this commands. 
I wish to delete the node-red-contrib-tesla and use only TeslaMate in my node-red flow if possible. 

Thanks a lot in advance 
Denis

**Comment by LelandSindt** [comment]
.. working on a response..

**Comment by LelandSindt** [comment]
You will also need to set `API_TOKEN` https://github.com/tobiasehlert/teslamateapi#authentication

TeslaMateAPI does not monitor MQTT to invoke commands. Commands are invoked via a HTTP. 

The simplest example I can provide to start/stop charging utilizes curl.. 

**Start charging**

```
curl -i -H "Authorization: Bearer <YOUR API_TOKEN> " -X POST http://<YOUR HOST>:8080/api/v1/cars/1/command/charge_start
```
https://tesla-api.timdorr.com/vehicle/commands/charging#post-api-1-vehicles-id-command-charge_start

**Stop charging**

```
curl -i -H "Authorization: Bearer <YOUR API_TOKEN> " -X POST http://<YOUR HOST>:8080/api/v1/cars/1/command/charge_stop
```
https://tesla-api.timdorr.com/vehicle/commands/charging#post-api-1-vehicles-id-command-charge_stop

... I am not familiar with node red, but it looks like HTTP POST requests including Headers is supported.. 
https://stevesnoderedguide.com/node-red-http-request-node-beginners

**Comment by denisjoshua** [comment]
Thanks a lot for the answer... but I think I missing something. 
If I can not use the commands with TeslaMate, why I must enable the commands like [here](https://github.com/tobiasehlert/TeslaMateApi#commands) please ? 
But any way... I think that this type of commands is too complex for me. 

Thanks a lot again 
Denis

**Comment by LelandSindt** [comment]
```
If I can not use the commands with TeslaMate, why I must enable the commands like here please ?
```
I am not entirely sure what you mean...

If you are so inclined, I would encourage you to get TeslaMateAPI configured and talking to TeslaMate and then work with a simple program like `curl` or a tool like [postman](https://www.postman.com/) to learn to make HTTP calls to TeslaMateAPI to retrieve (GET) information or send (POST) commands.

**Comment by denisjoshua** [comment]
Sorry... I mean that in the page https://github.com/tobiasehlert/TeslaMateApi#commands
there is a procedure for activate the commands.
But after that, there is no procedure in the doc. page, that explain you how to use this commands with TeslaMate.
Thanks again 
Denis

**Comment by tobiasehlert** [comment]
> But after that, there is no procedure in the doc. page, that explain you how to use this commands with TeslaMate.

Hi @denisjoshua,
there is a reference on the last line of the section mentioning the timdoor/tesla-api documentation on what you need to provide when sending commands to the commands section. Basically we just proxy it right away to Tesla, so TeslaMate is not involved in the requests more than that we provide the authentication on the request.
Hope this helps :)

**Comment by denisjoshua** [comment]
Thanks for the answer Tobias, and also because is the first time we "talk", 
thanks a lot for this wonderful and free software :-) 

But because I'm not a programmer... I mean I'm a Cobol programmer but this have nothing to do with TeslaMate ambient, 
I just want to ask you something. 

In order to future implement of TeslaMate, it's possible to make a MQTT topic, (for example /teslamate/cars/1/send_command) 
and then monitor that topic in order to proxy it right away to Tesla ? 
So then I can send a topic like: /teslamate/cars/1/send_command/charge_start [on/off] in order to start charge. 

Obviously this type of command will be activated from the env variable for security reason for anyone that need it. 

Thanks a lot again 
Denis

**Comment by tobiasehlert** [comment]
Hi @denisjoshua,

I don't think a MQTT topic would be the best solution, since we'd need a data-body for some of the requests to Tesla, but of course not all. Your's regarding starting and stopping of charge would not require one, but others door. And I would prefer to have it as lightweight as possible. One of the reasons we just tunnel the requests to Tesla instead of applying some own logic.
And well, it would go to do a serializing of a JSON string that we would pass on, but nothing that I have in mind of implementing as it looks right now. :)

Regards,
Tobias

**Comment by denisjoshua** [comment]
Ok thanks a lot... I'll continue to use the node-red-contrib-tesla for now :-( 
 
Thanks a lot fot TeslaMate and lot of congrats :-) 
Denis

**Comment by tobiasehlert** [comment]
Thanks @denisjoshua :)
